### ISSUE TITLE
During training, the accuracy of RCNN is decreasing from the beginning to 92.5498, is it normal?

### ISSUE THREAD

**Issue by hdjsjyl** [bowenc0221/Decoupled-Classification-Refinement#10]
During training, the accuracy of RCNN is decreasing from the beginning to 92.5498, is it normal?
Any advice will be appreciated, thanks

**Comment by bowenc0221** [comment]
It's not normal. The accuracy of RCNN should be increasing during training.

I would suggest you debug RPN first. That is, train RPN and test the recall of RPN first to make sure the proposals are correct.

You can use [train_rpn.py](https://github.com/bowenc0221/Decoupled-Classification-Refinement/blob/master/faster_rcnn/function/train_rpn.py) and [test_rpn.py](https://github.com/bowenc0221/Decoupled-Classification-Refinement/blob/master/faster_rcnn/function/test_rpn.py).

**Comment by hdjsjyl** [comment]
@bowenc0221 , now the rpn part is normal, but rcnn part is not normal, let me try. Thanks

**Comment by hdjsjyl** [comment]
@bowenc0221 ,  For the end of training, rcnn accuracy could be 0.994567, but rpn accuracy is 90.234 or so. Moreover, all the scores predicted by dcr are nans. And the dcr accuracy is only 70.234 or so. Any advice will be appreciated, thanks.
