### ISSUE TITLE
Question about Boxes used in RCNN

### ISSUE THREAD

**Issue by JunweiLiang** [bowenc0221/Decoupled-Classification-Refinement#13]
Hi, do you use boxes from RPN (so usually is (1000, 4)), or boxes after faster-RCNN box regression (also (1000, 4)), or the final boxes after NMS?

**Comment by bowenc0221** [comment]
I use boxes after faster-RCNN box regression before NMS.

**Comment by JunweiLiang** [comment]
Minor question: so in Fig.4 of your paper, there shouldn't be an arrow from RPN proposals pointing to RCNN training? What does that arrow mean?

**Comment by bowenc0221** [comment]
The main reason is to make the figure looks clean without overlapping arrows @weiyc 
It should come from the Faster R-CNN outputs as stated in Section 4.2.

**Comment by JunweiLiang** [comment]
Thanks. Have you tried using RPN box instead? If you weren't using class-agnostic regressor head then the regression output depends on the Faster RCNN classification output, which I think may negatively affect the Decoupled RCNN performance.

**Comment by bowenc0221** [comment]
The bounding box regression in Faster R-CNN is class agnostic. That is, all classes shared the same box for each proposal.
