### ISSUE TITLE
what is the meaning of 'class agnostic' ?

### ISSUE THREAD

**Issue by hdjsjyl** [bowenc0221/Decoupled-Classification-Refinement#14]
what is the meaning of 'class agnostic' ?

**Comment by bowenc0221** [comment]
'class agnostic' proposals/detections/bounding box regression means the generated boxes are independent of class.

Take bounding box regression for example, if there are 20 classes (in VOC) not including background, for each proposal, Faster R-CNN has a classifier to classify its class and a bounding box regression branch to generate 20 transformation parameters. If it is class1, then detection is generated using the first transformation parameter, if it is classe, then the second...

If the bounding box regression is 'class agnostic', this branch will generate only one transformation parameter shared by all 20 classes.

**Comment by hdjsjyl** [comment]
@bowenc0221 It is very clear. Thank you very much!
