### ISSUE TITLE
Can you upload your training log? 

### ISSUE THREAD

**Issue by hdjsjyl** [bowenc0221/Decoupled-Classification-Refinement#8]
@bowenc0221 Hi, thanks for your work again. I want to check the log information about loss, accuracy variance of RPN and RCNN, can you upload your training log file? Thanks

**Comment by bowenc0221** [comment]
@hdjsjyl Currently I could not access the machine I used for training (it is a remote machine not owned by me), I will upload the log files if the problem is fixed.

**Comment by hdjsjyl** [comment]
@bowenc0221 , it is ok. After training, when I used the trained model to draw the predictions on the image, I found it is totally wrong. That's why I want to compare my log file with yours. Thanks.
